version: "3"
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb+srv://sa:sa@cluster0.a0pc9kv.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0;
